name: CI Workflow Advanced

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Starting Job"

    - name: Run actions/checkout@v3
      uses: actions/checkout@v3

    - name: Fix Git Safe Directory
      run: git config --global --add safe.directory '*'

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Check Env
      run: |
        python --version
        pip --version
        ls -R

    - name: Install dependencies
      run: |
        pip install mlflow pandas scikit-learn

    - name: Run mlflow project
      run: |
        # 1. Set URI agar mlruns tersimpan di root folder (penting untuk langkah selanjutnya)
        export MLFLOW_TRACKING_URI=file:$(pwd)/mlruns
        
        # 2. Masuk ke folder project
        cd MLProject
        
        # 3. Jalankan MLflow dengan context '.' (folder saat ini)
        mlflow run . --env-manager=local --experiment-name rf-ci-experiment

    - name: Get latest MLflow run_id
      id: get_run_id
      run: |
        # Script ini akan mencari di folder root/mlruns (sesuai setting URI di atas)
        RUN_ID=$(ls -td mlruns/*/* | head -1 | awk -F'/' '{print $(NF)}')
        echo "Latest Run ID: $RUN_ID"
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

    - name: Install Python dependencies
      run: pip install requests

    - name: Upload to Google Drive (Disimpan ke GitHub Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: mlruns

    - name: Build Docker Model
      env:
        MLFLOW_TRACKING_URI: file:./mlruns
        RUN_ID: ${{ steps.get_run_id.outputs.run_id }}
      run: |
        echo "Building Docker for Run ID: $RUN_ID"
        mlflow models build-docker \
          -m "runs:/$RUN_ID/model" \
          -n "my-rf-model:latest" \
          --enable-mlserver

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker Image
      run: |
        docker tag my-rf-model:latest ${{ secrets.DOCKER_USERNAME }}/rf-ci-model:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/rf-ci-model:latest

    - name: Post Log in to Docker Hub
      run: echo "Logged out"

    - name: Post Set up Python 3.12.7
      run: echo "Python cleaned up"

    - name: Complete job
      run: echo "Job Done"